#!/usr/bin/env bash
# ==============================================================================
# NAME: bootstrap.sh
# DESCRIPTION: SessionStart hook for the ARCUS plugin.
#              Stages the deterministic helper scripts into the active workspace
#              at .arcus/bin/ and records the plugin home (ARCUS_HOME) and
#              version in .arcus/env so skills can resolve bundled scripts and
#              agent specs regardless of where the plugin is cached on disk.
#
# It is idempotent and MUST be run at the start of every ARCUS entry point
# rather than relied upon as a host hook. Only Claude Code fires this as a
# SessionStart hook; GitHub Copilot CLI reads hooks from .github/hooks/ and
# ~/.copilot/hooks/ in its own schema, so a plugin-bundled Claude-format hook
# never executes there. Re-running unconditionally also re-stages .arcus/bin
# after a plugin upgrade — the staged copy is otherwise a snapshot that never
# expires, and a repo bootstrapped by one host keeps serving that host's
# older scripts to every other host.
# ==============================================================================

set -eu

# Resolve the plugin root from this script's own location. This works in every
# host (VS Code, Copilot CLI, Claude Code) and does not depend on a plugin-root
# token being defined.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
ARCUS_HOME="$(cd "$SCRIPT_DIR/.." && pwd)"

# The hook runs with the workspace as the current directory.
WORKSPACE_ROOT="$(pwd)"

# Only bootstrap inside a git repository (the ARCUS pipeline requires git).
if [ ! -d "$WORKSPACE_ROOT/.git" ]; then
    exit 0
fi

BIN_DIR="$WORKSPACE_ROOT/.arcus/bin"
mkdir -p "$BIN_DIR"

# Stage every helper script except this bootstrapper.
for script in "$ARCUS_HOME"/scripts/*.sh; do
    [ -e "$script" ] || continue
    name="$(basename "$script")"
    [ "$name" = "bootstrap.sh" ] && continue
    cp "$script" "$BIN_DIR/$name"
    chmod +x "$BIN_DIR/$name"
done

# Stage sourced libraries (the top-level glob above does not recurse into lib/).
if [ -d "$ARCUS_HOME/scripts/lib" ]; then
    LIB_DIR="$BIN_DIR/lib"
    mkdir -p "$LIB_DIR"
    for lib in "$ARCUS_HOME"/scripts/lib/*.sh; do
        [ -e "$lib" ] || continue
        name="$(basename "$lib")"
        cp "$lib" "$LIB_DIR/$name"
        chmod +x "$LIB_DIR/$name"
    done
fi

# Record the plugin home so skills can locate bundled resources (templates,
# references, agent specs) if they ever need an absolute path. The version is
# stamped too: `.arcus/bin` is a COPY, so without it there is no way to tell a
# freshly-staged workspace from one carrying months-old scripts.
ARCUS_VERSION="$(node -p "require('$ARCUS_HOME/.claude-plugin/plugin.json').version" 2>/dev/null || echo unknown)"
cat > "$WORKSPACE_ROOT/.arcus/env" <<ENV
# Generated by the ARCUS bootstrap. Do not edit by hand.
ARCUS_HOME=$ARCUS_HOME
ARCUS_VERSION=$ARCUS_VERSION
ENV

# Make sure the working area is ignored by git.
if ! grep -q "^\.arcus" "$WORKSPACE_ROOT/.gitignore" 2>/dev/null; then
    printf "\n# --- ARCUS Artifacts ---\n.arcus/\n" >> "$WORKSPACE_ROOT/.gitignore"
fi

echo "[ARCUS] Ready. Helper scripts staged at .arcus/bin/ (ARCUS_HOME=$ARCUS_HOME)."
