#!/usr/bin/env bash
# ==============================================================================
# NAME: bootstrap.sh
# DESCRIPTION: SessionStart hook for the ARCUS plugin.
#              Stages the deterministic helper scripts into the active workspace
#              at .arcus/bin/ and records the plugin home (ARCUS_HOME) in
#              .arcus/env so skills can resolve bundled scripts regardless of
#              where the plugin is cached on disk.
#
# This runs automatically when an agent session starts in a workspace with the
# arcus plugin enabled. It is idempotent and safe to run repeatedly.
# ==============================================================================

set -eu

# Resolve the plugin root from this script's own location. This works in every
# host (VS Code, Copilot CLI, Claude Code) and does not depend on a plugin-root
# token being defined.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
ARCUS_HOME="$(cd "$SCRIPT_DIR/.." && pwd)"

# The hook runs with the workspace as the current directory.
WORKSPACE_ROOT="$(pwd)"

# Only bootstrap inside a git repository (the ARCUS pipeline requires git).
if [ ! -d "$WORKSPACE_ROOT/.git" ]; then
    exit 0
fi

BIN_DIR="$WORKSPACE_ROOT/.arcus/bin"
mkdir -p "$BIN_DIR"

# Stage every helper script except this bootstrapper.
for script in "$ARCUS_HOME"/scripts/*.sh; do
    [ -e "$script" ] || continue
    name="$(basename "$script")"
    [ "$name" = "bootstrap.sh" ] && continue
    cp "$script" "$BIN_DIR/$name"
    chmod +x "$BIN_DIR/$name"
done

# Stage sourced libraries (the top-level glob above does not recurse into lib/).
if [ -d "$ARCUS_HOME/scripts/lib" ]; then
    LIB_DIR="$BIN_DIR/lib"
    mkdir -p "$LIB_DIR"
    for lib in "$ARCUS_HOME"/scripts/lib/*.sh; do
        [ -e "$lib" ] || continue
        name="$(basename "$lib")"
        cp "$lib" "$LIB_DIR/$name"
        chmod +x "$LIB_DIR/$name"
    done
fi

# Record the plugin home so skills can locate bundled resources (templates,
# references, the model-strategy skill) if they ever need an absolute path.
cat > "$WORKSPACE_ROOT/.arcus/env" <<ENV
# Generated by the ARCUS bootstrap hook. Do not edit by hand.
ARCUS_HOME=$ARCUS_HOME
ENV

# Make sure the working area is ignored by git.
if ! grep -q "^\.arcus" "$WORKSPACE_ROOT/.gitignore" 2>/dev/null; then
    printf "\n# --- ARCUS Artifacts ---\n.arcus/\n" >> "$WORKSPACE_ROOT/.gitignore"
fi

echo "[ARCUS] Ready. Helper scripts staged at .arcus/bin/ (ARCUS_HOME=$ARCUS_HOME)."
