#!/usr/bin/env bash
# ==============================================================================
# NAME: bootstrap.sh
# DESCRIPTION: SessionStart hook for the Agent Forge Kit (AFK) plugin.
#              Stages the deterministic helper scripts into the active workspace
#              at .aforge/bin/ and records the plugin home (AFORGE_HOME) in
#              .aforge/env so skills can resolve bundled scripts regardless of
#              where the plugin is cached on disk.
#
# This runs automatically when an agent session starts in a workspace with the
# agent-forge plugin enabled. It is idempotent and safe to run repeatedly.
# ==============================================================================

set -eu

# Resolve the plugin root from this script's own location. This works in every
# host (VS Code, Copilot CLI, Claude Code) and does not depend on a plugin-root
# token being defined.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
AFORGE_HOME="$(cd "$SCRIPT_DIR/.." && pwd)"

# The hook runs with the workspace as the current directory.
WORKSPACE_ROOT="$(pwd)"

# Only bootstrap inside a git repository (the AFK pipeline requires git).
if [ ! -d "$WORKSPACE_ROOT/.git" ]; then
    exit 0
fi

BIN_DIR="$WORKSPACE_ROOT/.aforge/bin"
mkdir -p "$BIN_DIR"

# Stage every helper script except this bootstrapper.
for script in "$AFORGE_HOME"/scripts/*.sh; do
    [ -e "$script" ] || continue
    name="$(basename "$script")"
    [ "$name" = "bootstrap.sh" ] && continue
    cp "$script" "$BIN_DIR/$name"
    chmod +x "$BIN_DIR/$name"
done

# Record the plugin home so skills can locate bundled resources (templates,
# references, the model-strategy skill) if they ever need an absolute path.
cat > "$WORKSPACE_ROOT/.aforge/env" <<ENV
# Generated by the Agent Forge Kit bootstrap hook. Do not edit by hand.
AFORGE_HOME=$AFORGE_HOME
ENV

# Make sure the working area is ignored by git.
if ! grep -q "^\.aforge" "$WORKSPACE_ROOT/.gitignore" 2>/dev/null; then
    printf "\n# --- Agent-Forge Artifacts ---\n.aforge/\n" >> "$WORKSPACE_ROOT/.gitignore"
fi

echo "[AFK] Ready. Helper scripts staged at .aforge/bin/ (AFORGE_HOME=$AFORGE_HOME)."
